class DuplicateError(Exception):
    pass

class EmptyError(Exception):
    pass